POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/60a21440-9922-4d98-aa8d-727d934fc2e8
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o video treinamento",
    "duration": 180
}
###
DELETE  http://localhost:3333/videos/fa616e7e-59ca-4b75-a8b4-7c0db01c2569