POST https://node-js-mhfn.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###
GET https://node-js-mhfn.onrender.com/videos

###
PUT https://node-js-mhfn.onrender.com/videos/"9c8412f8-f319-4f0e-9049-e8f9c8fc5296
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o video treinamento",
    "duration": 180
}
###
DELETE  https://node-js-mhfn.onrender.com/videos/fa616e7e-59ca-4b75-a8b4-7c0db01c2569