POST https://node-js-mhfn.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###
GET https://node-js-mhfn.onrender.com/videos

###
PUT https://node-js-mhfn.onrender.com/videos/8c127413-49a5-4ffd-a11d-c19a05bd54f7
Content-Type: application/json

{
    "title": "Video 03",
    "description": "Esse é o video para excluir",
    "duration": 180
}
###
DELETE  https://node-js-mhfn.onrender.com/videos/8c127413-49a5-4ffd-a11d-c19a05bd54f7